services:
  jenkins-agent:
    image: jenkins-agent-linux-dind:latest
    container_name: new-laptop-linux-container-dind
    restart: unless-stopped
    # DNS Configuration
    privileged: true
    dns:
      - 192.168.36.250
    group_add:
      - docker
    environment:
      JENKINS_URL: "https://jenkins.bgfamily.ca"
      AGENT_SECRET: "a9b37ce31ef2aad7392343a5e1c949ca3e1d422af3215bdbf82c43ce14fc3ceb"
      AGENT_NAME: "new-laptop-linux-container-dind"
      AGENT_WORKDIR: "/home/jenkins" # Double backslashes to escape properly in YAML
    volumes:
      - jenkins-dind-storage:/var/lib/docker
volumes:
  jenkins-dind-storage:
