services:
  jenkins-agent:
    image: jenkins-agent-linux-dind:latest
    container_name: new-laptop-linux-container-dind
    restart: unless-stopped
    # DNS Configuration
    privileged: true
    dns:
      - 192.168.36.250
    group_add:
      - docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Environment Variables
    environment:
      JENKINS_URL: "https://jenkins.bgfamily.ca"
      AGENT_SECRET: "48e83b94e789d24e8cce97dc64c2254c302824d237ac7d84b601d3e6dfe6d4fd"
      AGENT_NAME: "new-laptop-container-dind"
      AGENT_WORKDIR: "/home/jenkins" # Double backslashes to escape properly in YAML
